/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface KeepitBannerContainer {
    'showFullBanner': boolean;
    'text1': string;
    'text2': string;
    'text3': string;
    'text4': string;
  }
  interface KeepitSideDrawer {
    'makeOpen': () => Promise<void>;
    'open': boolean;
    'titleName': string;
  }
}

declare global {


  interface HTMLKeepitBannerContainerElement extends Components.KeepitBannerContainer, HTMLStencilElement {}
  var HTMLKeepitBannerContainerElement: {
    prototype: HTMLKeepitBannerContainerElement;
    new (): HTMLKeepitBannerContainerElement;
  };

  interface HTMLKeepitSideDrawerElement extends Components.KeepitSideDrawer, HTMLStencilElement {}
  var HTMLKeepitSideDrawerElement: {
    prototype: HTMLKeepitSideDrawerElement;
    new (): HTMLKeepitSideDrawerElement;
  };
  interface HTMLElementTagNameMap {
    'keepit-banner-container': HTMLKeepitBannerContainerElement;
    'keepit-side-drawer': HTMLKeepitSideDrawerElement;
  }
}

declare namespace LocalJSX {
  interface KeepitBannerContainer {
    'onRedirect'?: (event: CustomEvent<any>) => void;
    'onToggleBunner'?: (event: CustomEvent<any>) => void;
    'showFullBanner'?: boolean;
    'text1'?: string;
    'text2'?: string;
    'text3'?: string;
    'text4'?: string;
  }
  interface KeepitSideDrawer {
    'open'?: boolean;
    'titleName'?: string;
  }

  interface IntrinsicElements {
    'keepit-banner-container': KeepitBannerContainer;
    'keepit-side-drawer': KeepitSideDrawer;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'keepit-banner-container': LocalJSX.KeepitBannerContainer & JSXBase.HTMLAttributes<HTMLKeepitBannerContainerElement>;
      'keepit-side-drawer': LocalJSX.KeepitSideDrawer & JSXBase.HTMLAttributes<HTMLKeepitSideDrawerElement>;
    }
  }
}


